-- อันนี้ผมทำไว้รันใน Supabase SQL Editor

create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table todos enable row level security;


create policy "Public todos are viewable by everyone."
  on todos for select
  using ( true );

create policy "Everyone can insert todos."
  on todos for insert
  with check ( true );
  
create policy "Everyone can update todos."
  on todos for update
  using ( true );
